"""add postings, ledger_entries, account_balances tables

Revision ID: 48b626cbef28
Revises: 87f876c16108
Create Date: 2026-09-17 14:47:44.676429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '48b626cbef28'
down_revision: Union[str, None] = '87f876c16108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_service', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.Enum('TRANSFER', 'PAYMENT', 'DEPOSIT', 'WITHDRAWAL', 'REFUND', name='posting_type'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_service', 'source_id', 'type', name='uq_postings_source_idempotency')
    )
    op.create_table('account_balances',
    sa.Column('account_id', sa.UUID(), nullable=False),
    # create_type=False: account_kind already exists, created by the
    # previous migration for ledger_accounts.kind. Without this,
    # create_table() tries to CREATE TYPE account_kind again and fails.
    # Must be the dialect-specific postgresql.ENUM, not generic sa.Enum:
    # empirically, create_type=False on sa.Enum is *not* honored by
    # create_table()/create_all() — it still emits CREATE TYPE and fails
    # with "already exists." Only postgresql.ENUM(..., create_type=False)
    # actually suppresses it. Confirmed by executing both against a real
    # database before settling on this.
    sa.Column('kind', postgresql.ENUM('USER_WALLET', 'EXTERNAL_FUNDING', 'EXTERNAL_PAYOUT', 'MERCHANT_SETTLEMENT', 'FEES', 'SUSPENSE', name='account_kind', create_type=False), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('held_minor', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind != 'USER_WALLET' OR balance_minor - held_minor >= 0", name='ck_account_balances_wallet_available_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('posting_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.Enum('DEBIT', 'CREDIT', name='entry_direction'), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_minor > 0', name='ck_ledger_entries_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_posting_id'), 'ledger_entries', ['posting_id'], unique=False)
    # ### end Alembic commands ###

    # Every existing ledger_account (the system accounts seeded by the
    # previous migration) needs a balance row from the moment it exists —
    # create_posting() locks account_balances rows unconditionally, so a
    # missing row would make any posting touching a system account fail.
    # A wallet created after this migration gets its balance row inserted
    # by the wallet-creation service code instead (step 4), atomically
    # with the ledger_accounts row.
    op.execute(
        "INSERT INTO account_balances (account_id, kind, balance_minor, held_minor, version) "
        "SELECT id, kind, 0, 0, 0 FROM ledger_accounts"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_posting_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_table('account_balances')
    op.drop_table('postings')
    # ### end Alembic commands ###

    # account_kind is NOT dropped here — it was created by the previous
    # migration and is still used by ledger_accounts.kind, which this
    # downgrade does not touch. Only the two enum types *this* migration
    # created are this migration's responsibility to clean up.
    sa.Enum(name='entry_direction').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='posting_type').drop(op.get_bind(), checkfirst=True)
