"""create ledger_accounts table

Revision ID: 87f876c16108
Revises: 
Create Date: 2026-09-17 14:42:03.289064

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f876c16108'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ledger_accounts_table = sa.table(
    "ledger_accounts",
    sa.column("id", sa.UUID),
    # Must match the real column's native enum type, not sa.String: the
    # asyncpg driver rejects an implicit varchar -> enum cast that
    # psycopg2 would have allowed silently.
    sa.column(
        "kind",
        sa.Enum(
            "USER_WALLET",
            "EXTERNAL_FUNDING",
            "EXTERNAL_PAYOUT",
            "MERCHANT_SETTLEMENT",
            "FEES",
            "SUSPENSE",
            name="account_kind",
        ),
    ),
    sa.column("owner_user_id", sa.UUID),
    sa.column("currency", sa.String),
)

# One of each system account kind, per currency (spec Section 8.1, 6.2).
_SYSTEM_ACCOUNT_KINDS = [
    "EXTERNAL_FUNDING",
    "EXTERNAL_PAYOUT",
    "MERCHANT_SETTLEMENT",
    "FEES",
    "SUSPENSE",
]
# Deliberately not imported from fincore_common.money.SUPPORTED_CURRENCIES:
# a migration must keep doing exactly what it did when it was written,
# even if that shared list gains a currency later. Hardcoding this
# snapshot is the correct Alembic practice, not an oversight.
_SUPPORTED_CURRENCIES = ["UZS", "USD"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ledger_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('USER_WALLET', 'EXTERNAL_FUNDING', 'EXTERNAL_PAYOUT', 'MERCHANT_SETTLEMENT', 'FEES', 'SUSPENSE', name='account_kind'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'FROZEN', 'CLOSED', name='account_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'USER_WALLET' AND owner_user_id IS NOT NULL) OR (kind != 'USER_WALLET' AND owner_user_id IS NULL)", name='ck_ledger_accounts_wallet_has_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_accounts_owner_user_id'), 'ledger_accounts', ['owner_user_id'], unique=False)
    op.create_index('uq_ledger_accounts_system_per_kind_currency', 'ledger_accounts', ['kind', 'currency'], unique=True, postgresql_where=sa.text('owner_user_id IS NULL'))
    op.create_index('uq_ledger_accounts_wallet_per_owner_currency', 'ledger_accounts', ['owner_user_id', 'currency'], unique=True, postgresql_where=sa.text('owner_user_id IS NOT NULL'))
    # ### end Alembic commands ###

    op.bulk_insert(
        ledger_accounts_table,
        [
            {
                "id": uuid.uuid4(),
                "kind": kind,
                "owner_user_id": None,
                "currency": currency,
            }
            for kind in _SYSTEM_ACCOUNT_KINDS
            for currency in _SUPPORTED_CURRENCIES
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ledger_accounts_wallet_per_owner_currency', table_name='ledger_accounts', postgresql_where=sa.text('owner_user_id IS NOT NULL'))
    op.drop_index('uq_ledger_accounts_system_per_kind_currency', table_name='ledger_accounts', postgresql_where=sa.text('owner_user_id IS NULL'))
    op.drop_index(op.f('ix_ledger_accounts_owner_user_id'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    # ### end Alembic commands ###

    # Same lesson as identity-service's first migration: drop_table()
    # does not drop the PostgreSQL native enum types backing these
    # columns, so a second upgrade would fail with "type already exists".
    sa.Enum(name='account_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='account_kind').drop(op.get_bind(), checkfirst=True)
