"""add holds table

Revision ID: af2fd3d94381
Revises: 48b626cbef28
Create Date: 2026-09-17 15:30:31.454618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2fd3d94381'
down_revision: Union[str, None] = '48b626cbef28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CAPTURED', 'RELEASED', 'EXPIRED', name='hold_status'), server_default='ACTIVE', nullable=False),
    sa.Column('source_service', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name='ck_holds_amount_positive'),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_service', 'source_id', name='uq_holds_source_idempotency')
    )
    op.create_index(op.f('ix_holds_account_id'), 'holds', ['account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holds_account_id'), table_name='holds')
    op.drop_table('holds')
    # ### end Alembic commands ###

    sa.Enum(name='hold_status').drop(op.get_bind(), checkfirst=True)
