"""add roles and user_roles tables

Revision ID: 378258c713c9
Revises: 6c6612273d94
Create Date: 2026-09-16 18:21:00.234713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '378258c713c9'
down_revision: Union[str, None] = '6c6612273d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


roles_table = sa.table(
    "roles",
    sa.column("name", sa.String),
    sa.column("description", sa.String),
)

_SEED_ROLES = [
    {"name": "USER", "description": "Standard authenticated customer."},
    {
        "name": "SUPPORT",
        "description": "Can review flagged operations and assist users; cannot perform admin actions.",
    },
    {
        "name": "ADMIN",
        "description": "Full administrative access, including user status management.",
    },
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_name'], ['roles.name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_name')
    )
    # ### end Alembic commands ###

    # Seed the fixed role set (spec Section 5) as part of the same
    # migration that creates the table, so `roles` is never empty in any
    # environment that has run migrations — registration depends on the
    # USER row existing.
    op.bulk_insert(roles_table, _SEED_ROLES)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
