"""create fraud_checks table

Revision ID: b5318f1d1118
Revises:
Create Date: 2026-09-18 16:41:48.855508

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5318f1d1118"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fraud_checks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("operation_type", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "decision", sa.Enum("ALLOW", "REVIEW", "BLOCK", name="fraud_decision"), nullable=False
        ),
        sa.Column("rules_triggered", sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "operation_id", "operation_type", name="uq_fraud_checks_operation_idempotency"
        ),
    )
    op.create_index(op.f("ix_fraud_checks_user_id"), "fraud_checks", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fraud_checks_user_id"), table_name="fraud_checks")
    op.drop_table("fraud_checks")
    # ### end Alembic commands ###
    # drop_table() does not drop the native enum type it implicitly
    # created — same lesson as every other service's first migration.
    sa.Enum(name="fraud_decision").drop(op.get_bind(), checkfirst=True)
