"""add merchants, payments, refunds tables

Revision ID: 05b49cb8770b
Revises: ba34b6997c93
Create Date: 2026-09-20 20:10:03.853393

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05b49cb8770b"
down_revision: str | None = "ba34b6997c93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "SUSPENDED", name="merchant_status"),
            server_default="ACTIVE",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchants_owner_user_id"), "merchants", ["owner_user_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=False),
        sa.Column("initiator_user_id", sa.UUID(), nullable=False),
        sa.Column("source_wallet_id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "PROCESSING",
                "SUCCESS",
                "FAILED",
                "EXPIRED",
                "PARTIALLY_REFUNDED",
                "REFUNDED",
                name="payment_status",
            ),
            server_default="CREATED",
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column(
            "fraud_decision",
            # create_type=False: this type already exists (created by
            # transfers' own migration) — without this, Postgres raises
            # "type already exists" (confirmed empirically).
            postgresql.ENUM("ALLOW", "REVIEW", "BLOCK", name="fraud_decision", create_type=False),
            nullable=True,
        ),
        sa.Column("hold_id", sa.UUID(), nullable=True),
        sa.Column("refunded_amount_minor", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("amount_minor > 0", name="ck_payments_amount_positive"),
        sa.CheckConstraint(
            "refunded_amount_minor >= 0 AND refunded_amount_minor <= amount_minor",
            name="ck_payments_refunded_amount_within_bounds",
        ),
        sa.ForeignKeyConstraint(
            ["idempotency_key_id"],
            ["idempotency_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("reference"),
    )
    op.create_index(
        op.f("ix_payments_idempotency_key_id"), "payments", ["idempotency_key_id"], unique=True
    )
    op.create_index(
        op.f("ix_payments_initiator_user_id"), "payments", ["initiator_user_id"], unique=False
    )
    op.create_index(op.f("ix_payments_merchant_id"), "payments", ["merchant_id"], unique=False)
    op.create_table(
        "refunds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", name="refund_status"),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("idempotency_key_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_minor > 0", name="ck_refunds_amount_positive"),
        sa.ForeignKeyConstraint(
            ["idempotency_key_id"],
            ["idempotency_keys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["payment_id"],
            ["payments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refunds_idempotency_key_id"), "refunds", ["idempotency_key_id"], unique=True
    )
    op.create_index(op.f("ix_refunds_payment_id"), "refunds", ["payment_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refunds_payment_id"), table_name="refunds")
    op.drop_index(op.f("ix_refunds_idempotency_key_id"), table_name="refunds")
    op.drop_table("refunds")
    op.drop_index(op.f("ix_payments_merchant_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_initiator_user_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_idempotency_key_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_merchants_owner_user_id"), table_name="merchants")
    op.drop_table("merchants")
    # ### end Alembic commands ###
    # drop_table() does not drop the native enum types it implicitly
    # created — same lesson as every other migration in this project.
    # fraud_decision is NOT dropped here: transfers (an earlier
    # migration) still owns and uses that type.
    sa.Enum(name="refund_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="payment_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="merchant_status").drop(op.get_bind(), checkfirst=True)
