"""create idempotency_keys and transfers tables

Revision ID: dca6ce635d5f
Revises: 
Create Date: 2026-09-17 16:57:05.891975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dca6ce635d5f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='idempotency_key_status'), server_default='IN_PROGRESS', nullable=False),
    sa.Column('response_status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_idempotency_keys_user_key')
    )
    op.create_index(op.f('ix_idempotency_keys_user_id'), 'idempotency_keys', ['user_id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('initiator_user_id', sa.UUID(), nullable=False),
    sa.Column('source_wallet_id', sa.UUID(), nullable=False),
    sa.Column('destination_wallet_id', sa.UUID(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transfer_status'), server_default='PENDING', nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('fraud_decision', sa.Enum('ALLOW', 'REVIEW', 'BLOCK', name='fraud_decision'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name='ck_transfers_amount_positive'),
    sa.CheckConstraint('source_wallet_id != destination_wallet_id', name='ck_transfers_source_ne_destination'),
    sa.ForeignKeyConstraint(['idempotency_key_id'], ['idempotency_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_index(op.f('ix_transfers_idempotency_key_id'), 'transfers', ['idempotency_key_id'], unique=True)
    op.create_index(op.f('ix_transfers_initiator_user_id'), 'transfers', ['initiator_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_initiator_user_id'), table_name='transfers')
    op.drop_index(op.f('ix_transfers_idempotency_key_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_idempotency_keys_user_id'), table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    # ### end Alembic commands ###

    # drop_table() does not drop the PostgreSQL native enum types backing
    # these columns — the identity-service/ledger-service lesson, applied
    # here for all three types this migration creates.
    sa.Enum(name='fraud_decision').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transfer_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='idempotency_key_status').drop(op.get_bind(), checkfirst=True)
